const categories=[{id:'hair',label:'髮型',icon:'✿'},{id:'top',label:'上衣',icon:'♧'},{id:'bottom',label:'裙子',icon:'⌁'},{id:'shoes',label:'鞋子',icon:'♡'},{id:'accessory',label:'配件',icon:'✧'}];
const items={hair:[{id:'brown',name:'柔柔長髮',art:'🧸'},{id:'pink',name:'粉紅雙馬尾',art:'🎀'},{id:'short',name:'俐落短髮',art:'✂️'},{id:'blue',name:'藍藍捲髮',art:'🫧'}],top:[{id:'pink',name:'草莓上衣',swatch:'pink'},{id:'blue',name:'天空襯衫',swatch:'blue'},{id:'yellow',name:'小黃花衣',swatch:'yellow'},{id:'mint',name:'薄荷背心',swatch:'mint'}],bottom:[{id:'lavender',name:'紫色短裙',swatch:'lavender'},{id:'denim',name:'牛仔短褲',swatch:'denim'},{id:'coral',name:'珊瑚蓬蓬裙',swatch:'coral'},{id:'mint',name:'薄荷長裙',swatch:'mint'}],shoes:[{id:'yellow',name:'檸檬小鞋',swatch:'yellow'},{id:'red',name:'紅色球鞋',swatch:'red'},{id:'blue',name:'海洋涼鞋',swatch:'blue'},{id:'pink',name:'粉紅芭蕾',swatch:'pink'}],accessory:[{id:'bow',name:'蝴蝶結',art:'🎀'},{id:'star',name:'星星髮夾',art:'⭐'},{id:'flower',name:'小花花',art:'🌼'},{id:'none',name:'不戴配件',art:'○'}]};
const state={category:'hair',selected:{hair:'brown',top:'pink',bottom:'lavender',shoes:'yellow',accessory:'bow'}};const $=s=>document.querySelector(s);const tabs=$('#categoryTabs'),grid=$('#itemsGrid'),count=$('#itemCount'),lookName=$('#lookName'),toast=$('#toast'),save=$('#saveButton');
function renderTabs(){tabs.innerHTML=categories.map(c=>`<button class="category-tab ${state.category===c.id?'active':''}" data-category="${c.id}" type="button"><span class="tab-icon">${c.icon}</span>${c.label}</button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;renderTabs();renderItems()})}
function renderItems(){const list=items[state.category];count.textContent=`${list.length} 件單品`;grid.innerHTML=list.map(i=>`<button class="item-card ${state.selected[state.category]===i.id?'selected':''}" data-item="${i.id}" type="button"><span class="item-art">${i.swatch?`<span class="swatch ${i.swatch}"></span>`:i.art}</span><span class="item-name">${i.name}</span></button>`).join('');grid.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.selected[state.category]=b.dataset.item;applyLook();renderItems()})}
function applyLook(){const s=state.selected;$('#hairLayer').className=`hair hair-${s.hair}`;$('#topLayer').className=`top top-${s.top}`;$('#bottomLayer').className=`bottom bottom-${s.bottom}`;$('#shoeLayer').className=`shoes shoes-${s.shoes}`;$('#accessoryLayer').className=`accessory accessory-${s.accessory}`;const n={lavender:'晴天小洋裝',denim:'活力小玩家',coral:'珊瑚公主',mint:'薄荷小精靈'};lookName.textContent=n[s.bottom]||'我的可愛造型';save.classList.remove('saved');save.innerHTML='<span>♡</span> 收藏造型'}
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2200)}
$('#randomButton').onclick=()=>{Object.keys(items).forEach(k=>state.selected[k]=items[k][Math.floor(Math.random()*items[k].length)].id);state.category=categories[Math.floor(Math.random()*categories.length)].id;applyLook();renderTabs();renderItems();showToast('叮！新的造型完成了 ✨')};save.onclick=()=>{localStorage.setItem('little-stylist-look',JSON.stringify(state.selected));save.classList.add('saved');save.innerHTML='<span>♥</span> 已收藏造型';showToast('已把這套可愛造型收藏起來！')};
try{const saved=localStorage.getItem('little-stylist-look');if(saved)state.selected={...state.selected,...JSON.parse(saved)}}catch(e){}renderTabs();renderItems();applyLook();
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installButton').hidden=false});$('#installButton').onclick=async()=>{if(deferred){deferred.prompt();deferred=null}else showToast('請用 Safari 的分享按鈕加入主畫面')};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
